2025-04-10 10:18:03,409 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:18:04,094 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:18:04,096 - INFO - Playstation : Game not found for title: Minecraft
2025-04-10 10:20:27,202 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:20:27,842 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:20:28,533 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:20:29,165 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:20:29,771 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:20:30,420 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:25,767 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:26,363 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:26,998 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:27,640 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:28,285 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:28,925 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:29,561 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:30,192 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:30,789 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:31,474 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:32,080 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:32,705 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:33,352 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:33,995 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:34,634 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:36,530 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:37,170 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:37,762 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:38,453 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:39,125 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:39,749 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:41,807 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:42,453 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:43,112 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:43,723 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:44,323 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:44,982 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:45,661 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:46,272 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:46,915 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:28:47,561 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:29:06,730 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:07,347 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:07,965 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:08,585 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:09,200 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:09,847 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:10,459 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:11,093 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:11,737 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:12,358 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:13,020 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:13,628 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:14,269 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:14,911 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:15,520 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:16,149 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:16,776 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:17,370 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:17,995 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:18,641 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:19,263 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:19,917 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:20,576 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:21,216 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:21,832 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:22,531 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:23,158 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:23,811 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:24,497 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:25,123 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:25,778 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:26,395 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:27,007 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:27,650 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:28,334 - INFO - Network error fetching game /en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:30,678 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:31,290 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:31,913 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:29:33,981 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/de-at/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:32:55,040 - ERROR - Exception on /game [POST]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 476, in wrapper
    signal.signal(signal.SIGALRM, timeout_handler)
NameError: name 'timeout_handler' is not defined
2025-04-10 10:33:02,995 - ERROR - Exception on /game [POST]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 476, in wrapper
    signal.signal(signal.SIGALRM, timeout_handler)
NameError: name 'timeout_handler' is not defined
2025-04-10 10:33:38,259 - ERROR - Exception on /game [POST]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 476, in wrapper
    signal.signal(signal.SIGALRM, timeout_handler)
NameError: name 'timeout_handler' is not defined
2025-04-10 10:34:03,852 - ERROR - Exception on /game [POST]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 476, in wrapper
    signal.signal(signal.SIGALRM, timeout_handler)
NameError: name 'timeout_handler' is not defined
2025-04-10 10:34:09,067 - ERROR - Exception on /game [POST]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 476, in wrapper
    signal.signal(signal.SIGALRM, timeout_handler)
NameError: name 'timeout_handler' is not defined
2025-04-10 10:35:06,102 - INFO - Network error fetching game /en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001: 403 Client Error: Forbidden for url: https://store.playstation.com/en-us/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:08,318 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:08,915 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:09,558 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:13,548 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:14,188 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:14,853 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:15,539 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:16,178 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:16,865 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:17,508 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:18,143 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:18,768 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:19,421 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/es-ar/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:21,880 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:22,484 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:23,110 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:23,742 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:24,393 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:25,058 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:25,693 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:26,308 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:26,953 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:27,591 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:28,219 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:28,902 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:29,559 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:30,217 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:30,833 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:31,461 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:32,132 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/ar-bh/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:34,201 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/fr-be/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:35:34,807 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/fr-be/product/UP4433-CUSA00744_00-MINECRAFTPS40001
2025-04-10 10:38:29,434 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-eu/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:38:37,154 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/fr-be/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:38:55,019 - INFO - 403 Client Error: Forbidden for url: https://store.playstation.com/en-kw/product/UP4433-PPSA17221_00-MINECRAFTPS50000
2025-04-10 10:39:21,788 - INFO - Playstation : Minecraft
2025-04-10 10:39:27,105 - INFO - ====== WebDriver manager ======
2025-04-10 10:39:27,342 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-10 10:39:27,346 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-10 10:39:27,346 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-10 10:39:27,499 - INFO - Driver downloading response is 200
2025-04-10 10:39:28,189 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-10 10:39:31,640 - INFO - ====== WebDriver manager ======
2025-04-10 10:39:31,900 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-10 10:39:31,904 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-10 10:39:31,905 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-10 10:39:32,049 - INFO - Driver downloading response is 200
2025-04-10 10:39:32,718 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-13 12:15:42,179 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 604, in get_games
    games = paginate(collection, page, per_page, filters)
  File "/home/king/parser/api_server.py", line 709, in paginate
    results = list(collection.find(query, {"_id": 0}).skip((page - 1) * per_page).limit(per_page))
  File "/home/king/parser/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 504, in skip
    raise ValueError("skip must be >= 0")
ValueError: skip must be >= 0
2025-04-13 13:08:09,900 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 604, in get_games
    games = paginate(collection, page, per_page, filters)
  File "/home/king/parser/api_server.py", line 709, in paginate
    results = list(collection.find(query, {"_id": 0}).skip((page - 1) * per_page).limit(per_page))
  File "/home/king/parser/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 504, in skip
    raise ValueError("skip must be >= 0")
ValueError: skip must be >= 0
2025-04-14 15:34:57,793 - INFO - ====== WebDriver manager ======
2025-04-14 15:34:58,022 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:34:58,025 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:34:58,025 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:34:58,177 - INFO - Driver downloading response is 200
2025-04-14 15:34:58,860 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:35:18,567 - INFO - ====== WebDriver manager ======
2025-04-14 15:35:18,788 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:35:18,792 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:35:18,792 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:35:18,943 - INFO - Driver downloading response is 200
2025-04-14 15:35:19,455 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:37:47,590 - INFO - ====== WebDriver manager ======
2025-04-14 15:37:47,888 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:37:47,893 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:37:47,893 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:37:48,045 - INFO - Driver downloading response is 200
2025-04-14 15:37:48,689 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:38:07,223 - INFO - ====== WebDriver manager ======
2025-04-14 15:38:07,433 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:38:07,436 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:38:07,436 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:38:07,583 - INFO - Driver downloading response is 200
2025-04-14 15:38:08,119 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:39:23,856 - INFO - ====== WebDriver manager ======
2025-04-14 15:39:24,181 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:39:24,185 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:39:24,185 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:39:24,327 - INFO - Driver downloading response is 200
2025-04-14 15:39:25,006 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:39:43,687 - INFO - ====== WebDriver manager ======
2025-04-14 15:39:43,951 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:39:43,955 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:39:43,955 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:39:44,109 - INFO - Driver downloading response is 200
2025-04-14 15:39:44,594 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:42:21,192 - INFO - ====== WebDriver manager ======
2025-04-14 15:42:21,460 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:42:21,463 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:42:21,463 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:42:21,619 - INFO - Driver downloading response is 200
2025-04-14 15:42:22,272 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:52:09,485 - INFO - ====== WebDriver manager ======
2025-04-14 15:52:09,814 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:52:09,818 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:52:09,818 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:52:09,969 - INFO - Driver downloading response is 200
2025-04-14 15:52:10,679 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-14 15:53:04,691 - INFO - ====== WebDriver manager ======
2025-04-14 15:53:04,980 - INFO - WebDriver version 135.0.7049.84 selected
2025-04-14 15:53:04,983 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:53:04,983 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/linux64/chromedriver-linux64.zip
2025-04-14 15:53:05,126 - INFO - Driver downloading response is 200
2025-04-14 15:53:05,613 - INFO - Driver has been saved in cache [/home/king/.wdm/drivers/chromedriver/linux64/135]
2025-04-18 16:43:03,284 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 602, in get_games
    collection = mongo.db.steam_games + mongo.db.xbox_games + mongo.db.playstation_games + mongo.db.nintendo_games
TypeError: unsupported operand type(s) for +: 'Collection' and 'Collection'
2025-04-18 16:43:23,687 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 602, in get_games
    collection = mongo.db.steam_games + mongo.db.xbox_games + mongo.db.playstation_games + mongo.db.nintendo_games
TypeError: unsupported operand type(s) for +: 'Collection' and 'Collection'
2025-04-18 16:48:15,176 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 604, in get_games
    games = paginate(collection, page, per_page, filters)
  File "/home/king/parser/api_server.py", line 711, in paginate
    results = list(collection.find(query, {"_id": 0}).skip((page - 1) * per_page).limit(per_page))
AttributeError: 'list' object has no attribute 'find'
2025-04-18 16:48:30,493 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 604, in get_games
    games = paginate(collection, page, per_page, filters)
  File "/home/king/parser/api_server.py", line 711, in paginate
    results = list(collection.find(query, {"_id": 0}).skip((page - 1) * per_page).limit(per_page))
AttributeError: 'list' object has no attribute 'find'
2025-04-21 11:55:13,309 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 11:55:24,686 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 11:55:35,373 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 11:58:04,139 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 11:58:10,202 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 11:58:28,121 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 12:04:27,985 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 12:20:58,640 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 605, in get_games
    for service_name in services:
NameError: name 'services' is not defined
2025-04-21 12:44:29,777 - ERROR - Exception on /games [GET]
Traceback (most recent call last):
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/king/parser/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/king/parser/api_server.py", line 600, in get_games
    games = paginate(coll, page, per_page, filters)
NameError: name 'coll' is not defined
2025-04-22 11:29:55,497 - INFO - ******************** Started Scheduler... ********************
2025-04-22 11:29:56,086 - INFO - ========== Starting scraper_nintendo.py... ==========
2025-04-22 11:29:56,090 - INFO - Process scraper_nintendo.py started with PID 154641
2025-04-22 11:29:56,453 - INFO - Waiting for fetching Nintendo games...
2025-04-22 11:29:57,390 - INFO - Fetched 1000 games in Nintendo.
